# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97c2647e91e879f495a41e94412f04216b602b4aa24f943599385d653c8ca35281c9f9e857672c9781334f0497688307117ad01da96da3a78f857e55e3c2a18e

test:
  secret_key_base: aa6c988e85d54cb362216c7bf27b4b7925288813b8402448af0051ed71ccd1a6b5a23bb1c3f7751b6edab4ee9b5571a81e1a2f651f99f461fff237ee5b691742

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
